#!/bin/bash
## check_unicorn.sh for check_unicorn in /Users/fresh/nagios/check_unicorn
##
## Made by Anthony Scalisi
## <scalisi.a@gmail.com>
##
## Started on  Mon May 28 15:25:47 2012 Anthony Scalisi
## Last update Mon May 28 18:58:21 2012 Anthony Scalisi
##

OK_STATE=0
WARNING_STATE=1
CRITICAL_STATE=2
UNKNOWN_STATE=3
EXPECTED_ARGS=1
E_BADARGS=65

if [ $# -ne $EXPECTED_ARGS ]
then
    echo "Usage: `basename $0` [number of workers expected]"
    exit ${UNKNOWN_STATE}
    exit $E_BADARGS
fi

count_unicorn=`ps awx | egrep unicorn | egrep -v "(grep|nagios|check_unicorn)" | wc -l`

if [[ "$count_unicorn" -ge "$1" ]]; then
	echo "OK - $count_unicorn unicorn processes running"
	exit ${OK_STATE}
#elif [[ "$count_unicorn" -gt "$1" ]]; then
#	echo "WARNING - Too many unicorn processes ($count_unicorn) running."
#	exit ${WARNING_STATE}
elif [[ "$count_unicorn" -lt $1 ]]; then
	echo "CRITICAL - only $count_unicorn unicorn processes are running !"
	exit ${CRITICAL_STATE}
else
    echo "UNKNOWN - Could not figure unicorn status. Please check it out ASAP."
    exit ${UNKNOW_STATE}
fi
